### ISSUE TITLE
Авторизация setup.py

### ISSUE THREAD

**Issue by completesoft** [completesoft/juventus#1]
Добавить авторизацию в setup.py
Перед любой операцией запрашивать административный пароль

```
import getpass
pw = getpass.getpass()
```

шифровать его в md5 и отправлять на сервер вместе с запросом в параметре "key"

```
{
	"action": "register",
	"name": "client-name-01",
        "key": "1a1dc91c907325c69271ddf0c944bc72"
}

```

**Comment by docent2010** [comment]
Закрывай ищщщью

**Comment by completesoft** [comment]
Запрос пароля должен быть только перед отправкой на сервер

**Comment by completesoft** [comment]
исправил
